### ISSUE TITLE
gentoo-kernel: include zfs

### ISSUE THREAD

**Issue by 65278** [adjust/gentoo-overlay#204]
we should add a zfs bundling because it does become tedious to fix this after every global kernel update.

**Comment by xmhd** [comment]
So I can think of two approaches to this, first up:

### 1) Bundle ZFS into kernel sources

Procedure:
- Add USE flag, e.g.. system-zfs to the kernel sources (e.g. gentoo-sources) ebuild

- Add conditional (i.e USE=-system-zfs):
    - ZFS sources fetching to SRC_URI
    - ZFS sources unpacking to src_unpack
    - If applicable, ZFS sources patching to src_prepare
    - ZFS sources configure to src_configure (e.g. cd $ZFS_SOURCES && econf && ./copy-builtin)
    - ZFS sources compilation to src_compile (e.g. cd $ZFS_SOURCES && emake)

Pros:
- ZFS now built into kernel, no more rebuilding zfs-kmod each new kernel.
- No forking of ebuilds or packages
- No extra logic required for rebuilding initramfs

Cons:
- Only works for ZFS - other external kmods (e.g. nvidia) still need manually rebuilt each time.



### 2) Utilise linux-mod eclass to force subslot rebuilds.

Mgorny (the magic man) has utilised this in Gentoo with his 'dist-kernel' (Distribution kernel) project.

Gorny's Procedure:

- Add some logic to linux-mod eclass, e.g. USE=dist-kernel and RDEPEND="virtual/dist-kernel:=" for forcing subslot rebuilds.
- virtual/dist-kernel package (similar to virtual/linux-sources) is a virtual for:
    - sys-kernel/gentoo-kernel
    - sys-kernel/gentoo-kernel-bin
    - sys-kernel/vanilla-kernel
- Create new 'dist-kernel-utils' eclass with pkg_postinst logic for rebuilding initramfs (currently forces dracut and not genkernel).
- Inherit dist-kernel-utils initramfs rebuild in external kmod packages where you wish to force a rebuild (currently only implemented in sys-fs/zfs).

Pros:
- _All_ external kernel module packages get rebuilt on each new kernel build, not only ZFS.

Cons:
- Gorny being Gorny has forced his opinion in places (e.g. naming of 'dist-kernel', use of dracut for initramfs generation).
- At the mercy of Gorny and his ways.
- Some light forking of ebuild(s) required.

My proposed solution:

- fork linux-mod eclass (doesn't change all that often, so not difficult to keep up with)
- add the same/similar logic for forcing subslot rebuilds, but to suit us (e.g. sys-kernel/gentoo-sources[buildkernel] USE flag) instead of Gorny's new virtual package.
- Add some initramfs generation logic and add it to linux-mod_pkg_postinst for conditionally regenerating initramfs if has_version sys-kernel/gentoo-sources[buildkernel]
All external kmod packages that are relevant (ZFS, NVIDIA, wireguard, virtualbox, vmware etc) all call linux-mod_pkg_postinst in their own pkg_postinst ebuild phase, so we can force an initramfs rebuild here so that we always have the latest version of these external kernel modules in our initramfs.

Pros:
- _All_ external kernel module packages get rebuilt on each new kernel build, not only ZFS
- Not at the mercy of Gorny and his ways.

Cons:
- Forking of a single (but slow changing) eclass


### Thoughts
I currently use a bundled ZFS into kernel sources solution on my personal machines, and have done for years now. I find it simplistic to maintain and the only real caveat is not bumping your kernel beyond the supported version listed @ OpenZFS upstream and having to manually define which version of ZFS that you wish to use.

_However_ if we have any plans to utilise other external kernel modules, then the second option may suit us better.

I am personally open to either solution, or anything else that is proposed. My only real wishes are getting what we want from the solution while keeping it simplistic and maintainable.

cc @monsieurp and anyone else who has an opinion on this stuff :-)

**Comment by xmhd** [comment]
new kernel ebuild will fix this
